---
title: "Part3_graph1HW10"
author: "Aaryan Jadhav"
date: "11/20/2019"
output: pdf_document
---

Load the libraries in
```{r, echo=TRUE, message = FALSE, error = FALSE, warning=FALSE}
library(RSQLite)
library(ggplot2)
library(tidyverse)
library(grid)
library(gridBase)
library(gridExtra)
grid.newpage()
```


Makes the dataframe for 2018 months and the ineffeciency (Total Seats - Seats Filled)
```{r, echo=TRUE, message = FALSE, error = FALSE}
DT = data.frame(
  month = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),
  Ineffeciency = c(1795726, 1795726, 795726, 1327422, 1299193, 1086968, 1291711, 1650673, 1733035, 1499018, 1352993, 1459601))
DT
```

Creates the original plot using ggplot. This plot looks at ineffeciency which is the number of seats empty on planes during a given month.
```{r, echo=TRUE, message = FALSE, error = FALSE}
usingGg <- ggplot(data=DT, aes(x=DT$month, y=DT$Ineffeciency, group=1)) +
  geom_line()+
  geom_point() + labs(title = "Ineffeciency (Seats - Passengers) of Flights by Month", x= "Month", y = "Ineffeciency")
```


Function used to recreate the plot using grid.
```{r, echo=TRUE, message = FALSE, error = FALSE}
my.grid.plot <- function(vals) {
  grid.newpage()
  grid.layout(1,2)
  top.vp <- viewport(width = 0.8, height = 0.8)
  pushViewport(top.vp)
  grid.xaxis(label = FALSE)
  grid.yaxis(label = FALSE)
  grid.text("Ineffeciency (Seats - Passengers) of Flights by Month", x=.4,y=1.0)
  grid.text("Ineffeciency", x=-0.05,y=0.5, just = "right",rot=90)
  grid.text("Month", x = 0.5, y = unit(-0.05, "npc"), just = "top")
  grid.points(x = unit(0.07, "npc"), y = unit(0.45, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.14, "npc"), y = unit(0.72, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.21, "npc"), y = unit(0.57, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.28, "npc"), y = unit(0.87, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.35, "npc"), y = unit(0.87, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.42, "npc"), y = unit(0.40, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.49, "npc"), y = unit(0.20, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.56, "npc"), y = unit(0.08, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.63, "npc"), y = unit(0.41, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.70, "npc"), y = unit(0.45, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.77, "npc"), y = unit(0.60, "npc"),size = unit(0.5, "char"))
  grid.points(x = unit(0.84, "npc"), y = unit(0.8, "npc"),size = unit(0.5, "char"))
  grid.lines(x = unit(c(0.07, 0.14), "npc"),y = unit(c(0.45, 0.72), "npc"))
  grid.lines(x = unit(c(0.14, 0.21), "npc"),y = unit(c(0.72, 0.57), "npc"))
  grid.lines(x = unit(c(0.21, 0.28), "npc"),y = unit(c(0.57, 0.87), "npc"))
  grid.lines(x = unit(c(0.28, 0.35), "npc"),y = unit(c(0.87, 0.87), "npc"))
  grid.lines(x = unit(c(0.35, 0.42), "npc"),y = unit(c(0.87, 0.40), "npc"))
  grid.lines(x = unit(c(0.42, 0.49), "npc"),y = unit(c(0.40, 0.20), "npc"))
  grid.lines(x = unit(c(0.49, 0.56), "npc"),y = unit(c(0.20, 0.08), "npc"))
  grid.lines(x = unit(c(0.56, 0.63), "npc"),y = unit(c(0.08, 0.41), "npc"))
  grid.lines(x = unit(c(0.63, 0.70), "npc"),y = unit(c(0.41, 0.45), "npc"))
  grid.lines(x = unit(c(0.70, 0.77), "npc"),y = unit(c(0.45, 0.60), "npc"))
  grid.lines(x = unit(c(0.77, 0.84), "npc"),y = unit(c(0.60, 0.8), "npc"))
  grid.text("Jan", x = unit(0.07, "npc"), y = unit(0.45-0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("Feb", x = unit(0.14, "npc"), y = unit(0.72+0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("Mar", x = unit(0.21, "npc"), y = unit(0.57-0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("Apr", x = unit(0.28, "npc"), y = unit(0.87+0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("May", x = unit(0.35, "npc"), y = unit(0.87+0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("Jun", x = unit(0.42, "npc"), y = unit(0.4-0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("July", x = unit(0.49, "npc"), y = unit(0.2-0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("Aug", x = unit(0.56, "npc"), y = unit(0.08-0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("Sep", x = unit(0.64, "npc"), y = unit(0.41-0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("Oct", x = unit(0.70, "npc"), y = unit(0.45-0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("Nov", x = unit(0.77, "npc"), y = unit(0.60-0.05, "npc"),gp = gpar(fontsize = 6))
  grid.text("Dec", x = unit(0.84, "npc"), y = unit(0.8-0.05, "npc"),gp = gpar(fontsize = 6))
}
```

Plotting the original plot
```{r, echo=TRUE, message = FALSE, error = FALSE}
usingGg
```

Plotting the recreation of the plot using grid.
```{r, echo=TRUE, message = FALSE, error = FALSE}
my.grid.plot(avg_delays$delayTime)
```

