---
title: "Homework 8 - Group"
date: "11/5/2019"
output: pdf_document
---

#### Group Members 
Melinda Ding (mjd4), Henry Creamer (hmc5), Caleigh Page (cap9), Aaryan Jadhav (aj52), Cole Morgan (cmm16)

#### Question 5 

```{r, echo=TRUE}
library(RSQLite)
library(stringr)
dcon <- dbConnect(SQLite(), dbname = "group10.db")
dbListTables(dcon)
```

Query the entire reviews table into a dataframe. 
```{r, echo=TRUE}
res <- dbSendQuery(conn = dcon, "
SELECT *
FROM reviews;")
reviews <- dbFetch(res, -1)
dbClearResult(res)
head(reviews)
```

Get the length of each review. 
```{r, echo=TRUE}
reviews$review_length = str_length(reviews$content)
head(reviews$review_length, 20)
```

Get the number of words in each review. 
```{r, echo=TRUE}
split_strings = str_split(reviews$content, " ")
reviews$review_word_count = sapply(split_strings, length)
head(reviews$review_word_count, 20)
```

Rename all the airport names to make it consistent with the flights table. 
```{r, echo=TRUE}
reviews$airport_name= str_replace_all(reviews$airport_name, "-airport", "")
head(reviews$airport_name, 20)
```


